---
title: "Observatório do Gás"
output: 
  flexdashboard::flex_dashboard: 
    theme:  cerulean # spacelab  #latly  #cerulean # 
    orientation: columns
    vertical_layout: fill
    storyboard: true
    social: menu
    logo: Marca_CERI_UmaCor_Branca.png
runtime: shiny
---
<style>
.navbar-logo img {
    position: absolute;
    right: 0px;  
}
img{
     max-height:48px;
}
</style>



```{r setup, include=FALSE}
  if(!require(flexdashboard)) {install.packages("flexdashboard")}
  library(flexdashboard)
  library(readxl)
  if(!require(tidyverse)) {install.packages("tidyverse")}
  library(tidyverse)
  library(plotly)
  if(!require(ggmap)) {install.packages("ggmap")}
  library(ggmap)
  if(!require(xts)) {install.packages("xts")}
  library(xts)
  
  if(!require(geobr)) {install.packages("geobr")}
  library(geobr)
  
  if(!require(ggiraph)) {install.packages("ggiraph")}
  library(ggiraph)
  
  if(!require(leaflet)) {install.packages("leaflet")}
  library(leaflet)
  
  if(!require(RColorBrewer)) {install.packages("RColorBrewer")}
  library(RColorBrewer)
  
  if(!require(sf)) {install.packages("sf")}
  library(sf)
  
  if(!require(geobr)) {install.packages("geobr")}
  library(geobr)

  if(!require(googlesheets4)) {install.packages("googlesheets4")}
  library(googlesheets4)
  
  library(kableExtra)
  library(leaflet.extras)
  #if(!require(d3heatmap)) {install.packages("d3heatmap")}
  #library(d3heatmap)
  library(htmltools)

  options(digits = 2, OutDec = ",")
  
  
#```{r child="miolodashboard.Rmd", echo=FALSE}
#```
```

# Abertura {data-icon="ion-android-navigate"}

## Column {.tabset}

```{r}
pacman::p_load(tidyverse, plotly, lubridate, stringr, stringi, geobr, mapview, leaflet, leafpop, ggplot2, plyr, readxl)
```

### Contratos Vigentes 
```{r}
vig <- read_excel('vigentes_ano.xlsx')
vig <- vig %>% dplyr::rename(ano = index, num = '0')
fig_vig <- plotly::plot_ly(vig, x= ~ano, y=~num, name = 'numero de contratos',
                           type = 'scatter', mode = 'lines', line = list(width = 6))
fig_vig <- fig_vig %>% 
  layout(#title = list(text = 'Número total de contratos vigentes por ano', size = 60),
         yaxis = list(title = 'Número de contratos vigentes', size = 40),
         xaxis = list(title = 'Ano', size = 40))
fig_vig <- fig_vig %>% plotly::layout(annotations =
                                      list(x = 0, y = -0.1,
                                           text = '<b> Fonte </b>: ANP.',
                                           showarrow = F,
                                           xref = 'paper',
                                           yref = 'paper',
                                           align = 'left',
                                           size = 40))
fig_vig
```

### Vigências por tipo de Comprador

```{r}
vig_c <- read_csv('vigencia_comprador.csv',
                  show_col_types = FALSE)
vig_c <- vig_c %>% dplyr::rename(livre = "consumidor livre",
                                 distribuidor_gnc = "distribuidor de gnc",
                                 distribuidor_gnl = "distribuidor de gnl",
                                 produtor_boca = "produtor (boca do poço)")
fig_vigc <- plotly::plot_ly(vig_c,
                            x = ~ano,
                            y =~comercializador,
                            type = 'scatter', mode = 'lines', line = list(width = 6),
                            name = 'Comercializador')
fig_vigc <- fig_vigc %>% add_trace(y = ~livre, 
                                   name = 'Consumidor Livre')
fig_vigc <- fig_vigc %>% add_trace(y = ~distribuidor_gnc, 
                                   name = 'Distribuidora de GNC')
fig_vigc <- fig_vigc %>% add_trace(y = ~distribuidor_gnl, 
                                   name = 'Distribuidora de GNL')
fig_vigc <- fig_vigc %>% add_trace(y = ~distribuidora, 
                                   name = 'Distribuidora Local (Gás Canalizado)')
fig_vigc <- fig_vigc %>% add_trace(y = ~outros, 
                                   name = 'Outros')
fig_vigc <- fig_vigc %>% add_trace(y = ~produtor_boca, 
                                   name = 'Produtor (boca do poço)')
fig_vigc <- fig_vigc %>% layout(showlegend = TRUE, legend = list(font = list(size = 18)),
                                yaxis = list(title = list(text ='Comercializador', size = 18)),
                                xaxis = list(title = list(text ='Ano', size = 30)))
fig_vigc
```

### Assinaturas

```{r}
ass <- read.csv('tabela_total_contratos.csv')
ass %>% dplyr::filter(ano >= '2020') -> ass

fig_ass <- plot_ly(ass, x = ~ano, y = ~comercializador, name = 'Comercializador',
                   type = 'scatter', mode = 'lines', line = list(width = 6))
fig_ass <- fig_ass %>% add_trace(y = ~consumidor.livre, name = 'Consumidor Livre')
fig_ass <- fig_ass %>% add_trace(y = ~distribuidor.de.gnc, name = 'Distribuidora de GNC')
fig_ass <- fig_ass %>% add_trace(y = ~distribuidor.de.gnl, name = 'Distribuidora de GNL')
fig_ass <- fig_ass %>% add_trace(y = ~distribuidora, name = 'Distribuidora Local de Gás Canalizado')
fig_ass <- fig_ass %>% add_trace(y = ~produtor..boca.do.poço., name = 'Produtor (boca do poço)')
fig_ass <- fig_ass %>% add_trace(y = ~outros, name = 'Outros')

fig_ass <- fig_ass %>% add_trace(ass , 
                                 x = ~ano, 
                                 y = ~total, 
                                 type = 'scatter',  
                                 mode = 'lines', 
                                 name = 'Total')
fig_ass <- fig_ass %>% layout(title = "Quantidade de Contratos Assinados por Tipo de Comprador",
                              yaxis = list(title = 'Número de Contratos'),
                              xaxis = list(title = 'Ano'), 
                              barmode = 'group',
                              autosize = TRUE)
fig_ass <- fig_ass %>% plotly::layout(annotations =
                                      list(x = 0, y = -0.1,
                                           text = '<b> Fonte </b>: ANP',
                                           showarrow = F,
                                           xref = 'paper',
                                           yref = 'paper',
                                           align = 'left'))
fig_ass

#tags$iframe(seamless="seamless", 
#                  src= 'fig_ass.html',
#                  width='70%', 
#                  height=800,
#                  style="border:none;")
```
